---
- name: Setup server
  hosts: all
  gather_facts: no

  tasks:
    - name: Install New Relic Java Agent
      include_role:
        name: newrelic
      vars:
        authentication_domain_id: 0f4dda55-888e-4f4d-abba-ac7b3417faba