- name: Set Variables
  set_fact:
    java_agent_version: 7.11.1
    output_dir: ./downloads

- name: Download the new Java Agent
  delegate_to: localhost
  shell: |
    wget https://download.newrelic.com/newrelic/java-agent/newrelic-agent/{{java_agent_version}}/newrelic-java.zip -O {{output_dir}}/newrelic-java.zip

- name: Unzip Java Agent Download
  delegate_to: localhost
  shell: |
    unzip -o {{output_dir}}/newrelic-java.zip -d {{output_dir}}

# These should be per app on host right?
##############################################################
- name: Copy New Relic Artifacts to Server
  synchronize:
    src: "{{output_dir}}/newrelic"
    dest: /opt/bin/lendingservices
    rsync_opts:
      - "--chmod=ugo+rwx"
  become: yes

- name: Set template vars
  set_fact:
    app_name: Test App
    labels: hello:world;foo:bar

- name: Template NewRelic Config
  template:
    src: ../../../templates/newrelic/newrelic.yml.j2
    dest: '/opt/bin/lendingservices/newrelic/newrelic.yml'

##############################################################