- name: Set Variables
  set_fact:
    java_agent_version: 7.11.1
    output_dir: ./downloads

- name: Download the new Java Agent
  delegate_to: localhost
  shell: |
    wget https://download.newrelic.com/newrelic/java-agent/newrelic-agent/{{java_agent_version}}/newrelic-java.zip -O {{output_dir}}/newrelic-java.zip

- name: Unzip Java Agent Download
  delegate_to: localhost
  shell: |
    unzip -o {{output_dir}}/newrelic-java.zip -d {{output_dir}}

# These should be per app on host right?
##############################################################
- name: Copy New Relic Artifacts to Server
  synchronize:
    src: "{{output_dir}}/newrelic"
    dest: /opt/bin
    rsync_opts:
      - "--chmod=ugo+rwx"
  become: yes

- name: Update License Key
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: "export NEW_RELIC_LICENSE_KEY="
    line: "export NEW_RELIC_LICENSE_KEY={{client_license_key}}"

- name: Update App Name
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: "export NEW_RELIC_APP_NAME="
    line: "export NEW_RELIC_APP_NAME=Foo-app"

- name: Update Labels
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: "export NEW_RELIC_LABELS="
    line: "export NEW_RELIC_LABELS=hello:world;foo:bar"

- name: Disable Application Logging
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: "export NEW_RELIC_APPLICATION_LOGGING_ENABLED="
    line: "export NEW_RELIC_APPLICATION_LOGGING_ENABLED=false"

##############################################################