- name: Set Vars
  set_fact:
    authentication_domain_id: 0f4dda55-888e-4f4d-abba-ac7b3417faba

- name: Get New Relic Service Account Key
  delegate_to: localhost
  run_once: true
  shell: |
    API_KEY=$(aws ssm get-parameter --name /secrets/new_relic/api_key --with-decryption --query "Parameter.Value" --output text)

    if [ -z "$API_KEY" ]; then
      echo Unable to read api key, are you logged in?
      exit 1
    fi

    echo $API_KEY
  register: api_key

- name: Set Api Key as Fact
  run_once: true
  set_fact:
    api_key: "{{ api_key.stdout }}"
  
- name: configure_client_management_account
  run_once: true
  import_tasks: configure_client_management_account.yml
- name: get_license_key
  run_once: true
  import_tasks: get_license_key.yml
- name: install_newrelic_java_agent
  import_tasks: install_newrelic_java_agent.yml